### ISSUE TITLE
Is it possible to set location of the modal ?

### ISSUE THREAD

**Issue by collegeimprovements** [Meemaw/react-micro-modal#19]
## 🚀 Feature Proposal

Set location of Modal. 
Is it possible to open/show modal on top of the screen ? 
Is it possible to set height/width of the modal ?

## Motivation
To create toast-like effect with modal.
To show login-form on top-middle of the screen when on desktop devices.

**Comment by Meemaw** [comment]
All of this is already possible through the styling props. I have added one Toast example to the [Storybook](https://meemaw.github.io/react-micro-modal/?path=/story/react-micro-modal--as-toast). However, there are other libraries that are built for Toasts specifically and are better for that purpose, e.g. [react-toastify](https://github.com/fkhadra/react-toastify).

You should figure login-form on top-middle out easily by yourself.
