### ISSUE TITLE
Include zIndex for Custom Modal Style

### ISSUE THREAD

**Issue by gary1410** [Meemaw/react-micro-modal#25]
## 🚀 Feature Proposal

Including zIndex in a styling the modal when using custom styles

## Motivation

I can't seem to get around not having zIndex for the modal-overlay.

## Example

I have zIndex's for some custom input fields that is ruining the the current modal implementation.  I noticed on on line 223 in index.ts that you've destructured the zIndex and not allowed for custom styling?  Why?  And how would I implement the need for the zIndex here? 

Thanks, the library is helpful and lightweight.  I just need to get passed the zIndex issue here.

**Comment by Meemaw** [comment]
Has been fixed in version 1.7.3. Please try it out and close the issue if it fixes your problem 😉

**Comment by gary1410** [comment]
Oh wow, thanks, I was about to put in a contribution, but it seems your commit was way more than what I would have done.  Thanks, I just pulled and it worked.
